### ISSUE TITLE
run building_text_classifier.ipynb out of memory

### ISSUE THREAD

**Issue by XuandongZhao** [meta-pytorch/opacus#234]
I want to run the tutorial of BERT. And my GPU is NVIDIA TITAN Xp, which has 12GB of memory. But OOM errors keep existing even when I set batch_size = 1. 
Do you know how much memory it requires or how to fix that?

**Comment by ffuuugor** [comment]
Hi, thanks for reporting the issue - the behaviour certainly doesn't look right. We'll investigate
